version: "3.8"

services:
  pharma_main:
    container_name: pharma_main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
    - ~/.aspnet/https:/https:ro